# Name of your site (displayed in the header)
name: thoughts about my computer hobbies

# Short bio or description (displayed in the header)
title: thoughts about my computer hobbies
description: I'm writting anything about my computer hobbies that gave me a smile after finding a solution

excerpt_separator: "<!--excerpt-->"
highlighter: rouge
#pygments: true
markdown: kramdown

url: http://fipnova51.github.io
title: My technical hobbies I've been working on
paginate: 10

