# Name of your site (displayed in the header)
name: fipnova51

# Short bio or description (displayed in the header)
description: First step with tinyPress / Jekyll and gitHub

excerpt_separator: "\n\n"
highlighter: rouge
#pygments: true
#markdown: kramdown

url: http://fipnova51.github.io
title: My technical hobbies I've been working on
paginate: 10

