# Name of your site (displayed in the header)
name: thoughts about my computer hobbies

# Short bio or description (displayed in the header)
title: Differents questions that keep my head looping on any computer questions
description: I'm writting anything about my computer hobbies that gave me a smile after finding a solution
url: http://fipnova51.github.io
paginate: 10

excerpt_separator: "<!--excerpt-->"
highlighter: rouge
#pygments: true
markdown: kramdown


